title: DEADMOUTH
author: 
email: 
description: >-
  
baseurl: "/deadmouth" # the subpath of your site, e.g. /blog
url: "" # your site's origin, e.g. https://forestry.io

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus
  - liquid_pluralize
  - jekyll-loading-lazy
  - jekyll-responsive-image

